export { default as HomePage } from "./Home";
export { default as AdminsPage } from "./Admins";
export { default as FuncionariosPage } from "./Funcionarios";
export { default as MedicosPage } from "./Medicos";
export { default as UnidadesPage } from "./Unidades";
export { default as ErrorPage } from "./Error";
export { default as LoginPage } from "./Login";
export { default as PacientesPage } from "./Pacientes";
export { default as ResetPage } from "./Reset";
